export const Actiontype = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: " REMOVE_SELECTED_PRODUCT",
  INCREMENT_PRODUCTS: " INCREMENT_PRODUCTS",
  DECREMENT_PRODUCTS: " DECREMENT_PRODUCTS",
  FAVORITE_OPEN_PRODUCT: "FAVORITE_PRODUCT",
  FAVORITE_CLOSE_PRODUCT: "FAVORITE_CLOSE_PRODUCT",
};
